
os: Visual Studio 2015

environment:
   matrix:
      - CONFIGURATION: Release
        PLATFORM: x64

install:
  - git submodule update --init --recursive

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - set CMAKE_URL="https://cmake.org/files/v3.13/cmake-3.13.0-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps > nul
  - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir Build && cd Build
  - cmake .. -G "Visual Studio 14 2015 Win64"
  - cmake --build . --target Kiwi --config %CONFIGURATION%

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
  - ISCC Scripts\setup-x64.iss
  - mkdir Kiwi
  - copy %APPVEYOR_BUILD_FOLDER%\Kiwi-x64-setup.exe %APPVEYOR_BUILD_FOLDER%\Kiwi\Kiwi-x64-setup.exe
  - 7z a Kiwi-windows-64.zip %APPVEYOR_BUILD_FOLDER%\Kiwi

artifacts:
  - path: '*.zip'

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
        secure: ZtKK8yOVkgIf+6Vm0jQLCbjCjuTiln3w2k/xMHI/kgardyCVtZ6plKI5O8lR3NNY
    artifact: /.*\.zip/
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true

notifications:
  - provider: Email
    on_build_status_changed: false
