
os: Visual Studio 2015

environment:
   matrix:
      - MSVS: 2015
        MSBUILD: 14.0
        CONFIGURATION: Release
        PLATFORM: Win32
      - MSVS: 2015
        MSBUILD: 14.0
        CONFIGURATION: Release
        PLATFORM: x64

install:
    - git submodule update --init --recursive
    - set PATH=C:\Python27;%PATH%
    - curl -o ..\flip-demo.zip -L -k  http://developer.irisate.com.s3-website-us-east-1.amazonaws.com/files/flip-demo-windows-c47e41da05.zip
    - cd ..
    - 7z x flip-demo.zip -o./flip-demo
    - set KIWI_FLIP_LIB_x64=%cd%/flip-demo/lib/VS2015/x64/Release
    - set KIWI_FLIP_INCLUDE_x64=%cd%/flip-demo/include
    - set KIWI_FLIP_LIB_WIN32=%cd%/flip-demo/lib/VS2015/Win32/Release
    - set KIWI_FLIP_INCLUDE_WIN32=%cd%/flip-demo/include
    - set KIWI_BOOST_INCLUDE=C:\Libraries\boost_1_63_0
    - set KIWI_BOOST_LIB_x64=C:\Libraries\boost_1_63_0\lib64-msvc-14.0
    - set KIWI_BOOST_LIB_WIN32=C:\Libraries\boost_1_63_0\lib32-msvc-14.0
    - cd %APPVEYOR_BUILD_FOLDER%
    - if "%APPVEYOR_REPO_BRANCH%"=="master" (set KIWI_DEPLOY=release) else (set KIWI_DEPLOY=draft)

build_script:
    - python .\Scripts\configure.py -c %CONFIGURATION% -p %PLATFORM%
    - python .\Scripts\build.py -c %CONFIGURATION% -p %PLATFORM%

after_build:
    - set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\Build\Release\%PLATFORM%\KiwiBuild\%CONFIGURATION%
    - 7z a Kiwi_%PLATFORM%.zip %BUILD_DIR%\Kiwi.exe %BUILD_DIR%\*.dll
    - 7z a Kiwi_Server_%PLATFORM%.zip %BUILD_DIR%\Server.exe

artifacts:
  - path: '*.zip'

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
        secure: ZtKK8yOVkgIf+6Vm0jQLCbjCjuTiln3w2k/xMHI/kgardyCVtZ6plKI5O8lR3NNY
    artifact: /.*\.zip/
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true
      KIWI_DEPLOY: 'draft'

  - provider: GitHub
    auth_token:
        secure: ZtKK8yOVkgIf+6Vm0jQLCbjCjuTiln3w2k/xMHI/kgardyCVtZ6plKI5O8lR3NNY
    artifact: /.*\.zip/
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true
      KIWI_DEPLOY: 'release'

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:

  # Email
  - provider: Email
    on_build_status_changed: false
