
os: Visual Studio 2015

environment:
   matrix:
      - MSVS: 2015
        MSBUILD: 14.0
        CONFIGURATION: Release
        PLATFORM: Win32
      - MSVS: 2015
        MSBUILD: 14.0
        CONFIGURATION: Release
        PLATFORM: x64

install:
    - git submodule update --init --recursive "ThirdParty/Juce"
    - git submodule update --init --recursive "ThirdParty/concurrentqueue"
    - git submodule update --init --recursive "ThirdParty/Beast"
    - set PATH=C:\Python27;%PATH%
    - cd %APPVEYOR_BUILD_FOLDER%
    - if "%APPVEYOR_REPO_BRANCH%"=="master" (set KIWI_DEPLOY=release) else (set KIWI_DEPLOY=draft)

build_script:
    - python .\Scripts\configure.py -c %CONFIGURATION% -p %PLATFORM%
    - python .\Scripts\build.py -c %CONFIGURATION% -p %PLATFORM%

after_build:
    - if "%PLATFORM%"=="x64" ("C:\Program Files (x86)\Inno Setup 5\ISCC.exe" Scripts\setup-x64.iss)
    - if "%PLATFORM%"=="Win32" ("C:\Program Files (x86)\Inno Setup 5\ISCC.exe" Scripts\setup-Win32.iss)
    - set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\Build\Release\%PLATFORM%\KiwiBuild\%CONFIGURATION%
    - if "%PLATFORM%"=="x64" (7z a Kiwi_%PLATFORM%.zip %BUILD_DIR%\Kiwi-x64-setup.exe)
    - if "%PLATFORM%"=="Win32" (7z a Kiwi_%PLATFORM%.zip %BUILD_DIR%\Kiwi-win32-setup.exe)

artifacts:
  - path: '*.zip'

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
        secure: ZtKK8yOVkgIf+6Vm0jQLCbjCjuTiln3w2k/xMHI/kgardyCVtZ6plKI5O8lR3NNY
    artifact: /.*\.zip/
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true
      KIWI_DEPLOY: 'draft'

  - provider: GitHub
    auth_token:
        secure: ZtKK8yOVkgIf+6Vm0jQLCbjCjuTiln3w2k/xMHI/kgardyCVtZ6plKI5O8lR3NNY
    artifact: /.*\.zip/
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true
      KIWI_DEPLOY: 'release'

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:

  # Email
  - provider: Email
    on_build_status_changed: false
