
os: Visual Studio 2015

environment:
   matrix:
      - MSVS: 2015
        MSBUILD: 14.0
        CONFIGURATION: Release
        PLATFORM: x64

install:
    - git submodule update --init --recursive
    - set PATH=C:\Python27;%PATH%
    - cd %APPVEYOR_BUILD_FOLDER%
    - if "%APPVEYOR_REPO_BRANCH%"=="master" (set KIWI_DEPLOY=release) else (set KIWI_DEPLOY=draft)
    - cd %APPVEYOR_BUILD_FOLDER%/ThirdParty
    - curl -L https://github.com/pierreguillot/llvm-win/releases/download/v6.0.0/llvm-windows-x64-mt.zip -o llvm.zip
    - 7z x llvm.zip
    - rename llvm-windows-x64-mt llvm
    - cd %APPVEYOR_BUILD_FOLDER%
    - python ./Scripts/flip.py
    - python ./Scripts/boost.py
build_script:
    - mkdir Build && cd Build
    - cmake .. -G "Visual Studio 14 2015 Win64" -DUSE_LLVM_CONFIG=off -DLLVM_DIR=./ThirdParty/llvm/lib/cmake/llvm
    - cmake --build . --config %CONFIGURATION%
after_build:
    - C:\Program Files (x86)\Inno Setup 5\ISCC.exe" Scripts\setup-x64.iss
    - set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\Build\Release\%PLATFORM%\KiwiBuild\%CONFIGURATION%
    - 7z a Kiwi_%PLATFORM%.zip %BUILD_DIR%\Kiwi-x64-setup.exe

artifacts:
  - path: '*.zip'

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
        secure: ZtKK8yOVkgIf+6Vm0jQLCbjCjuTiln3w2k/xMHI/kgardyCVtZ6plKI5O8lR3NNY
    artifact: /.*\.zip/
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true
      KIWI_DEPLOY: 'draft'

  - provider: GitHub
    auth_token:
        secure: ZtKK8yOVkgIf+6Vm0jQLCbjCjuTiln3w2k/xMHI/kgardyCVtZ6plKI5O8lR3NNY
    artifact: /.*\.zip/
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true
      KIWI_DEPLOY: 'release'

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:

  # Email
  - provider: Email
    on_build_status_changed: false
