
os: Visual Studio 2015

environment:
   matrix:
      - CONFIGURATION: Release
        PLATFORM: x64

install:
  - git submodule update --init --recursive
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir Build && cd Build
  - cmake .. -G "Visual Studio 14 2015 Win64"
  - cmake --build . --target Kiwi --config %CONFIGURATION%
after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - "C:\Program Files (x86)\Inno Setup 5\ISCC.exe" Scripts\setup-x64.iss
  - 7z a Kiwi_%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\Build\Release\%PLATFORM%\KiwiBuild\%CONFIGURATION%\Kiwi-x64-setup.exe

artifacts:
  - path: '*.zip'

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
        secure: ZtKK8yOVkgIf+6Vm0jQLCbjCjuTiln3w2k/xMHI/kgardyCVtZ6plKI5O8lR3NNY
    artifact: /.*\.zip/
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true

notifications:
  - provider: Email
    on_build_status_changed: false
