
os: Visual Studio 2015
clone_depth: 3

environment:
   matrix:
      - MSVS: 2015
        MSBUILD: 14.0
        CONFIGURATION: Release
        PLATFORM: Win32
      - MSVS: 2015
        MSBUILD: 14.0
        CONFIGURATION: Release
        PLATFORM: x64

install:
    - git submodule update --init --recursive --depth 2 "ThirdParty/Juce"
    - git submodule update --init --recursive --depth 2 "ThirdParty/cpr"
    - set PATH=C:\Python27;%PATH%

build_script:
    - python .\Config\configure.py -c %CONFIGURATION% -p %PLATFORM%
    - python .\Config\build.py -c %CONFIGURATION% -p %PLATFORM%

after_build:
    - del /F /S /Q /A %APPVEYOR_BUILD_FOLDER%\Build\Release\%PLATFORM%\KiwiBuild\Bin\%CONFIGURATION%\*.ilk
    - 7z a Kiwi_%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\Build\Release\%PLATFORM%\KiwiBuild\Bin\%CONFIGURATION%\Kiwi.exe

artifacts:
  - path: '*.zip'

deploy:
  provider: GitHub
  auth_token:
    secure: ZtKK8yOVkgIf+6Vm0jQLCbjCjuTiln3w2k/xMHI/kgardyCVtZ6plKI5O8lR3NNY
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:

  # Email
  - provider: Email
    on_build_status_changed: false
