
environment:
   matrix:
      - CONFIGURATION: Debug
        PLATFORM: Win32
#     - CONFIGURATION: Release
#       PLATFORM: Win32
      - CONFIGURATION: Debug
        PLATFORM: x64
#     - CONFIGURATION: Release
#       PLATFORM: x64

os: Visual Studio 2015

# scripts to run before build
build_script:
    - echo Running cmake...
    - mkdir build
    - cd build
    - cmake ..
    - dir
    - cmake --build .
    - test_dsp.exe

# build_script:
#    - mkdir build
#    - cd build
#    - cmake ..
#    - make
#    - ./test_dsp
#    - ./test_core


#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:

  # Email
  - provider: Email
    on_build_status_changed: false