
environment:
   matrix:
      - CONFIGURATION: Debug
        PLATFORM: Win32
      - CONFIGURATION: Debug
        PLATFORM: x64

os: Visual Studio 2015

build_script:
    - echo Running cmake...
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 15"
    - dir
    - cmake --build .
    - test_dsp.exe

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:

  # Email
  - provider: Email
    on_build_status_changed: false